# Generated by Django 5.1.5 on 2025-01-30 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
